"""W3ID redirect-config generation (v0.3.0, ADR-0014).

W3ID (https://w3id.org) is an Apache ``mod_rewrite`` redirector: a directory
named after a prefix holds an ``.htaccess`` that 302/303-redirects
``https://w3id.org/<prefix>/...`` to a deployment. To give an FDP persistent
identifiers, its ``identifier_base`` is a W3ID URL and the ``.htaccess`` points
at the current serving origin (``base_url``).

This module is pure: it produces the ``.htaccess`` body, a short README, and the
in-repo path, from the identifier base + serving base. The GitHub automation
(:mod:`fdp.metadata.pid.github`) consumes the result; the CLI prints it.
"""

from __future__ import annotations

from dataclasses import dataclass
from urllib.parse import urlsplit

__all__ = ["W3IDConfig", "build_w3id_config", "w3id_prefix_from"]

_W3ID_HOST = "w3id.org"


def w3id_prefix_from(identifier_base: str) -> str | None:
    """Extract the W3ID prefix from a ``https://w3id.org/<prefix>`` base.

    Returns the (possibly multi-segment) path under ``w3id.org`` with no leading
    or trailing slash, or ``None`` when ``identifier_base`` is not a W3ID URL.
    """
    parts = urlsplit(identifier_base)
    if parts.hostname != _W3ID_HOST:
        return None
    prefix = parts.path.strip("/")
    return prefix or None


@dataclass(frozen=True)
class W3IDConfig:
    """A ready-to-commit W3ID redirect entry."""

    prefix: str
    """The W3ID prefix directory, e.g. ``myfdp`` (or ``org/myfdp``)."""

    target: str
    """The serving origin redirected to (``base_url``), no trailing slash."""

    path: str
    """Path of the file inside the w3id.org repo: ``<prefix>/.htaccess``."""

    htaccess: str
    """The ``.htaccess`` body."""

    readme: str
    """A short human-readable description committed alongside as README.md."""


def build_w3id_config(
    *, identifier_base: str, serving_base: str, prefix: str | None = None
) -> W3IDConfig:
    """Build the W3ID redirect config for this deployment.

    Args:
        identifier_base: The persistent PID base (a ``https://w3id.org/<prefix>``
            URL). Used to derive the prefix when one is not given.
        serving_base: The serving origin requests are redirected to (``base_url``).
        prefix: Explicit W3ID prefix; required when ``identifier_base`` is not a
            W3ID URL, otherwise derived from it.

    Returns:
        A :class:`W3IDConfig` with the ``.htaccess``, README, and repo path.

    Raises:
        ValueError: No prefix could be determined.
    """
    resolved = (prefix or "").strip("/") or w3id_prefix_from(identifier_base)
    if not resolved:
        raise ValueError(
            "cannot determine the W3ID prefix: set identifier_base to a "
            "https://w3id.org/<prefix> URL or pass an explicit prefix"
        )
    target = serving_base.rstrip("/")
    htaccess = _build_htaccess(prefix=resolved, target=target)
    readme = _build_readme(prefix=resolved, target=target)
    return W3IDConfig(
        prefix=resolved,
        target=target,
        path=f"{resolved}/.htaccess",
        htaccess=htaccess,
        readme=readme,
    )


def _build_htaccess(*, prefix: str, target: str) -> str:
    return (
        f"# https://w3id.org/{prefix}  ->  {target}\n"
        f"# Persistent identifiers for the FAIR Data Point served at {target}.\n"
        "# Generated by `fdp pid w3id-config`; re-run it to re-point the target\n"
        "# when the deployment moves (the identifier base never changes).\n"
        "Options +FollowSymLinks\n"
        "RewriteEngine on\n"
        "\n"
        "# Preserve the sub-path and let the FDP do content negotiation (the\n"
        "# Accept header passes through a redirect). 302 keeps the FDP\n"
        "# re-pointable; switch to 301 once the serving URL is permanent.\n"
        f"RewriteRule ^(.*)$ {target}/$1 [R=302,L,NE]\n"
    )


def _build_readme(*, prefix: str, target: str) -> str:
    return (
        f"# w3id.org/{prefix}\n\n"
        f"Persistent identifier namespace for a FAIR Data Point (FDP) served at "
        f"<{target}>.\n\n"
        "Every record minted by the FDP has an IRI under "
        f"`https://w3id.org/{prefix}/`; this entry redirects those IRIs to the "
        "current deployment so they resolve. The FDP performs RDF content "
        "negotiation on the redirected request.\n\n"
        "Maintained automatically by the FDP (`fdp pid w3id-pr`). When the "
        "deployment moves, only the redirect target changes — the identifiers "
        "themselves are stable.\n"
    )
